galaxy_info:
  author: Nikolay Georgiev
  description: automates the generation of Let's Encrypt signed certificates with DNS challenges on Amazon's Route 53 (AWS)
  license: MIT
  min_ansible_version: 2.2
  platforms:
  - name: Ubuntu
    versions:
    - all
    - any
  galaxy_tags:
  - letsencrypt
  - route53
  - aws
  - dns
  - ssl

dependencies: [ geerlingguy.ansible, geerlingguy.pip ]
