---
- name: update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: install the required dependencies (Debian)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - openssl
  - python-boto
  - python-openssl
  when: ansible_os_family == 'Debian'
